// über LINQ!

// NEUES GERICHT HINZUFÜGEN (Create)

// ALLE GERICHTE AUSLESEN UND ANZEIGEN (Read)

// EIN GERICHT AKTUALISIEREN (Update)

// EIN GERICHT LÖSCHEN (Delete
 Console.WriteLine("Hello, EF Core!");