// <auto-generated />
using FruehstuecksrestaurantMore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace L01._2efc_mehrere_tabellen.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250917210558_ohneShadowProperty")]
    partial class ohneShadowProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DishIngredient", b =>
                {
                    b.Property<int>("IngredientsId")
                        .HasColumnType("int");

                    b.Property<int>("MoreDishesId")
                        .HasColumnType("int");

                    b.HasKey("IngredientsId", "MoreDishesId");

                    b.HasIndex("MoreDishesId");

                    b.ToTable("DishIngredient");
                });

            modelBuilder.Entity("FruehstuecksrestaurantMore.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("FruehstuecksrestaurantMore.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mehl",
                            Unit = "g"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Zucker",
                            Unit = "g"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ei",
                            Unit = "Stück"
                        });
                });

            modelBuilder.Entity("FruehstuecksrestaurantMore.Models.PreparationStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EinSehrKomischerNameFuerDenFremdschluessel")
                        .HasColumnType("int");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EinSehrKomischerNameFuerDenFremdschluessel");

                    b.ToTable("PreparationSteps");
                });

            modelBuilder.Entity("DishIngredient", b =>
                {
                    b.HasOne("FruehstuecksrestaurantMore.Models.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FruehstuecksrestaurantMore.Models.Dish", null)
                        .WithMany()
                        .HasForeignKey("MoreDishesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FruehstuecksrestaurantMore.Models.PreparationStep", b =>
                {
                    b.HasOne("FruehstuecksrestaurantMore.Models.Dish", "MoreDish")
                        .WithMany("PreparationSteps")
                        .HasForeignKey("EinSehrKomischerNameFuerDenFremdschluessel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MoreDish");
                });

            modelBuilder.Entity("FruehstuecksrestaurantMore.Models.Dish", b =>
                {
                    b.Navigation("PreparationSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
