// <auto-generated />
using FruehstuecksrestaurantMore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace L01._2efc_mehrere_tabellen.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DishIngredient", b =>
                {
                    b.Property<int>("IngredientsId")
                        .HasColumnType("int");

                    b.Property<int>("MoreDishesId")
                        .HasColumnType("int");

                    b.HasKey("IngredientsId", "MoreDishesId");

                    b.HasIndex("MoreDishesId");

                    b.ToTable("DishIngredient");

                    b.HasData(
                        new
                        {
                            IngredientsId = 1,
                            MoreDishesId = 1
                        },
                        new
                        {
                            IngredientsId = 5,
                            MoreDishesId = 1
                        },
                        new
                        {
                            IngredientsId = 1,
                            MoreDishesId = 2
                        },
                        new
                        {
                            IngredientsId = 2,
                            MoreDishesId = 2
                        },
                        new
                        {
                            IngredientsId = 3,
                            MoreDishesId = 2
                        },
                        new
                        {
                            IngredientsId = 4,
                            MoreDishesId = 2
                        });
                });

            modelBuilder.Entity("FruehstuecksrestaurantMore.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ein einfaches Spiegelei mit Salz.",
                            Name = "Spiegelei",
                            Price = 0m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ein süßer Klassiker.",
                            Name = "Pfannkuchen",
                            Price = 0m
                        });
                });

            modelBuilder.Entity("FruehstuecksrestaurantMore.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Eier",
                            Unit = "Stück"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mehl",
                            Unit = "g"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Zucker",
                            Unit = "g"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Milch",
                            Unit = "ml"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Salz",
                            Unit = "Prise"
                        });
                });

            modelBuilder.Entity("FruehstuecksrestaurantMore.Models.PreparationStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MoreDishId")
                        .HasColumnType("int");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MoreDishId");

                    b.ToTable("PreparationSteps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Instruction = "Pfanne erhitzen.",
                            MoreDishId = 1,
                            StepNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            Instruction = "Ei in die Pfanne schlagen.",
                            MoreDishId = 1,
                            StepNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            Instruction = "Mit Salz würzen.",
                            MoreDishId = 1,
                            StepNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            Instruction = "Mehl, Zucker, Milch und Eier zu einem Teig verrühren.",
                            MoreDishId = 2,
                            StepNumber = 1
                        },
                        new
                        {
                            Id = 5,
                            Instruction = "Etwas Teig in eine heiße Pfanne geben.",
                            MoreDishId = 2,
                            StepNumber = 2
                        },
                        new
                        {
                            Id = 6,
                            Instruction = "Von beiden Seiten goldbraun backen.",
                            MoreDishId = 2,
                            StepNumber = 3
                        });
                });

            modelBuilder.Entity("DishIngredient", b =>
                {
                    b.HasOne("FruehstuecksrestaurantMore.Models.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FruehstuecksrestaurantMore.Models.Dish", null)
                        .WithMany()
                        .HasForeignKey("MoreDishesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FruehstuecksrestaurantMore.Models.PreparationStep", b =>
                {
                    b.HasOne("FruehstuecksrestaurantMore.Models.Dish", "MoreDish")
                        .WithMany("PreparationSteps")
                        .HasForeignKey("MoreDishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MoreDish");
                });

            modelBuilder.Entity("FruehstuecksrestaurantMore.Models.Dish", b =>
                {
                    b.Navigation("PreparationSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
