// <auto-generated />
using System;
using Aufgabe_1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aufgabe_1.Migrations
{
    [DbContext(typeof(TicketVerwaltungDbContext))]
    [Migration("20251118222858_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aufgabe_1.Models.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Umsatz")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("Aufgabe_1.Models.Airplane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AirlineId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ManufactoringDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PilotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("PilotId");

                    b.ToTable("Airplanes");
                });

            modelBuilder.Entity("Aufgabe_1.Models.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kennung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Land")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("Aufgabe_1.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AirplaneId")
                        .HasColumnType("int");

                    b.Property<int>("CoPilotId")
                        .HasColumnType("int");

                    b.Property<int?>("FlyFromId")
                        .HasColumnType("int");

                    b.Property<int?>("FlyToId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GateCloses")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GateId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GateOpens")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kennung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PilotId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TakeOff")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AirplaneId");

                    b.HasIndex("CoPilotId");

                    b.HasIndex("FlyFromId");

                    b.HasIndex("FlyToId");

                    b.HasIndex("GateId");

                    b.HasIndex("PilotId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Aufgabe_1.Models.Gate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TerminalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TerminalId");

                    b.ToTable("Gates");
                });

            modelBuilder.Entity("Aufgabe_1.Models.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("Aufgabe_1.Models.Pilot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pilots");
                });

            modelBuilder.Entity("Aufgabe_1.Models.Terminal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AirportId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AirportId");

                    b.ToTable("Terminals");
                });

            modelBuilder.Entity("Aufgabe_1.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BoughtOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FlightId")
                        .HasColumnType("int");

                    b.Property<int?>("PassengerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("PassengerId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Aufgabe_1.Models.Airplane", b =>
                {
                    b.HasOne("Aufgabe_1.Models.Airline", "Airline")
                        .WithMany("Airplane")
                        .HasForeignKey("AirlineId");

                    b.HasOne("Aufgabe_1.Models.Pilot", null)
                        .WithMany("GeflogeneFlugzeuge")
                        .HasForeignKey("PilotId");

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("Aufgabe_1.Models.Flight", b =>
                {
                    b.HasOne("Aufgabe_1.Models.Airplane", "Airplane")
                        .WithMany()
                        .HasForeignKey("AirplaneId");

                    b.HasOne("Aufgabe_1.Models.Pilot", "CoPilot")
                        .WithMany("GeflogeneFlügeCopilot")
                        .HasForeignKey("CoPilotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aufgabe_1.Models.Airport", "FlyFrom")
                        .WithMany()
                        .HasForeignKey("FlyFromId");

                    b.HasOne("Aufgabe_1.Models.Airport", "FlyTo")
                        .WithMany()
                        .HasForeignKey("FlyToId");

                    b.HasOne("Aufgabe_1.Models.Gate", "Gate")
                        .WithMany("Flights")
                        .HasForeignKey("GateId");

                    b.HasOne("Aufgabe_1.Models.Pilot", "Pilot")
                        .WithMany("GeflogeneFlügePilot")
                        .HasForeignKey("PilotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airplane");

                    b.Navigation("CoPilot");

                    b.Navigation("FlyFrom");

                    b.Navigation("FlyTo");

                    b.Navigation("Gate");

                    b.Navigation("Pilot");
                });

            modelBuilder.Entity("Aufgabe_1.Models.Gate", b =>
                {
                    b.HasOne("Aufgabe_1.Models.Terminal", null)
                        .WithMany("Gates")
                        .HasForeignKey("TerminalId");
                });

            modelBuilder.Entity("Aufgabe_1.Models.Terminal", b =>
                {
                    b.HasOne("Aufgabe_1.Models.Airport", null)
                        .WithMany("Terminals")
                        .HasForeignKey("AirportId");
                });

            modelBuilder.Entity("Aufgabe_1.Models.Ticket", b =>
                {
                    b.HasOne("Aufgabe_1.Models.Flight", "Flight")
                        .WithMany("Tickets")
                        .HasForeignKey("FlightId");

                    b.HasOne("Aufgabe_1.Models.Passenger", "Passenger")
                        .WithMany("Tickets")
                        .HasForeignKey("PassengerId");

                    b.Navigation("Flight");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("Aufgabe_1.Models.Airline", b =>
                {
                    b.Navigation("Airplane");
                });

            modelBuilder.Entity("Aufgabe_1.Models.Airport", b =>
                {
                    b.Navigation("Terminals");
                });

            modelBuilder.Entity("Aufgabe_1.Models.Flight", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Aufgabe_1.Models.Gate", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("Aufgabe_1.Models.Passenger", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Aufgabe_1.Models.Pilot", b =>
                {
                    b.Navigation("GeflogeneFlugzeuge");

                    b.Navigation("GeflogeneFlügeCopilot");

                    b.Navigation("GeflogeneFlügePilot");
                });

            modelBuilder.Entity("Aufgabe_1.Models.Terminal", b =>
                {
                    b.Navigation("Gates");
                });
#pragma warning restore 612, 618
        }
    }
}
